title: Joshua Hanson, Niagara based Frontend Developer - eCommerce, Magento, WordPress, Xamarin, Shopify
author: Josh Hanson
email: josh@amory.co
description: > # this means to ignore newlines until "baseurl:"
  Frontend Developer, building brands, online stores, and experiences @Form & Affect. Former eCommerce developer @Northern Commerce, and WordPress and Mobile Developer @Niagara College Research & Innovation

twitter_username: joshhanson
github_username:  joshuahanson

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

sass:
    style: compressed
